version: '3.7'

services:
  api:
    build: .
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - 8000:8000
    depends_on:
      - db
    environment: &api-environment
      DJANGO_ENV: dev
      DJANGO_SECRET_KEY: secret_key
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      NEW_RELIC_CONFIG_FILE: newrelic.ini
      EMAIL_USE_SSL: 0
      EMAIL_USE_TLS: 0
      EMAIL_HOST: host
      EMAIL_HOST_USER: user
      EMAIL_HOST_PASSWORD: password
      EMAIL_PORT: port
      DEFAULT_FROM_EMAIL: default
    command: newrelic-admin run-program python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
