version: "3.7"

x-app-config: &app-config
  DJANGO_ENV: dev
  DJANGO_SECRET_KEY: secret_key
  REDIS_HOST: redis
  REDIS_PORT: 6379

x-db-config: &db-config
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  DATABASE_PASSWORD: pgpassword
  DATABASE_HOST: db
  DATABASE_PORT: 5432
  POSTGRES_PASSWORD: pgpassword
  EMAIL_USE_SSL: 0
  EMAIL_USE_TLS: 0
  EMAIL_HOST: host
  EMAIL_HOST_USER: user
  EMAIL_HOST_PASSWORD: password
  EMAIL_PORT: port
  DEFAULT_FROM_EMAIL: default

services:
  api:
    image: userapp_api
    build:
      context: .
    environment:
      <<: *app-config
      <<: *db-config
    depends_on:
      - db
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  db:
    image: postgres:12.5-alpine
    environment: *db-config
    logging:
      driver: none
    ports:
      - "5432:5432"
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
volumes:
  sqlvolume:
