# Generated by Django 4.2 on 2023-08-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_tag_user_role_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(null=True),
        ),
    ]
