# Generated by Django 4.2 on 2023-11-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_user_date_of_birth_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(max_length=300),
        ),
    ]
